# Generated by Django 5.2.5 on 2025-09-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pointimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='pict_url',
            field=models.ImageField(upload_to='barbers'),
        ),
    ]
