# Generated by Django 5.2.5 on 2025-09-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_admin_email_remove_admin_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='name',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='surname',
        ),
    ]
